#!/bin/sh
opam install uri
make clean && make && make examples
ocamlfind  ocamlopt -bin-annot -c -o _build/examples/git2/foreign/git2.cmi -package bytes -package unix -package bigarray -package str -package uri -package integers    -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers" -I _build/examples/git2/foreign  -I _build/src/ctypes  -I _build/src/ctypes-foreign-base  -I _build/src/ctypes-foreign-unthreaded examples/git2/foreign/git2.mli
ocamlfind  opt -bin-annot -c -o _build/examples/git2/foreign/git2.cmx -package bytes -package unix -package bigarray -package str -package uri -package integers   -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package unix -package bigarray -package str -package uri -package integers    -I _build/examples/git2/foreign  -I _build/src/ctypes  -I _build/src/ctypes-foreign-base  -I _build/src/ctypes-foreign-unthreaded examples/git2/foreign/git2.ml
ocamlfind  opt -bin-annot -c -o _build/examples/git2/foreign/git2_cmd.cmx -package bytes -package unix -package bigarray -package str -package uri -package integers   -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package unix -package bigarray -package str -package uri -package integers    -I _build/examples/git2/foreign  -I _build/src/ctypes  -I _build/src/ctypes-foreign-base  -I _build/src/ctypes-foreign-unthreaded examples/git2/foreign/git2_cmd.ml
ocamlfind  opt -I _build -linkpkg -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package unix -package bigarray -package str -package uri -package integers   _build/ctypes.cmxa _build/ctypes-foreign-base.cmxa _build/ctypes-foreign-unthreaded.cmxa -o _build/git2.native _build/examples/git2/foreign/git2.cmx _build/examples/git2/foreign/git2_cmd.cmx  -cclib -Wl,--no-as-needed -cclib -lgit2
ocamlfind  opt -bin-annot -c -o _build/examples/git2/stub-generation/bindings/git2_bindings.cmx -package bytes -package str -package uri -package unix -package bigarray -package integers   -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers    -I _build/examples/git2/stub-generation/bindings  -I _build/src/ctypes examples/git2/stub-generation/bindings/git2_bindings.ml
ocamlfind  opt -I _build -linkpkg -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers   _build/ctypes.cmxa -o _build/git2-stubs.native _build/examples/git2/stub-generation/bindings/git2_bindings.cmx  -cclib -Wl,--no-as-needed
ocamlfind  ocamlc -package bytes -package str -package uri -package unix -package bigarray -package integers   -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"   -c -o _build/examples/git2/stub-generation/bindings/git2_bindings.cmo -I _build/examples/git2/stub-generation/bindings  -I _build/src/ctypes examples/git2/stub-generation/bindings/git2_bindings.ml
ocamlfind  ocamlc -a -linkall -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"    -package bytes -package str -package uri -package unix -package bigarray -package integers   -o _build/git2-stubs.cma _build/examples/git2/stub-generation/bindings/git2_bindings.cmo -cclib -Wl,--no-as-needed
ocamlfind  opt -a -linkall -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers     -o _build/git2-stubs.cmxa _build/examples/git2/stub-generation/bindings/git2_bindings.cmx -cclib -Wl,--no-as-needed
ocamlfind  opt -shared -linkall -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers   -o _build/git2-stubs.cmxs _build/examples/git2/stub-generation/bindings/git2_bindings.cmx  -cclib -Wl,--no-as-needed
ocamlfind  opt -bin-annot -c -o _build/examples/git2/stub-generation/stub-generator/git2_stub_generator.cmx -package bytes -package str -package uri -package unix -package bigarray -package integers   -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers    -I _build/examples/git2/stub-generation/stub-generator  -I _build/src/ctypes  -I _build/src/cstubs  -I _build/src/ctypes-foreign-base  -I _build/src/ctypes-foreign-unthreaded  -I _build/examples/git2/stub-generation/bindings examples/git2/stub-generation/stub-generator/git2_stub_generator.ml
ocamlfind  opt -I _build -linkpkg -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers   _build/ctypes.cmxa _build/cstubs.cmxa _build/ctypes-foreign-base.cmxa _build/ctypes-foreign-unthreaded.cmxa _build/git2-stubs.cmxa -o _build/git2-stub-generator.native _build/examples/git2/stub-generation/stub-generator/git2_stub_generator.cmx  -cclib -Wl,--no-as-needed
_build/git2-stub-generator.native
ocamlfind  opt -bin-annot -c -o _build/examples/git2/stub-generation/git2_generated.cmx -package bytes -package str -package uri -package unix -package bigarray -package integers   -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers    -I _build/examples/git2/stub-generation  -I _build/src/ctypes  -I _build/examples/git2/stub-generation/bindings examples/git2/stub-generation/git2_generated.ml
ocamlfind  opt -bin-annot -c -o _build/examples/git2/stub-generation/git2_stub_cmd.cmx -package bytes -package str -package uri -package unix -package bigarray -package integers   -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers    -I _build/examples/git2/stub-generation  -I _build/src/ctypes  -I _build/examples/git2/stub-generation/bindings examples/git2/stub-generation/git2_stub_cmd.ml
cd _build/examples/git2/stub-generation && ocamlfind  ocamlc -c -package bytes -package str -package uri -package unix -package bigarray -package integers   -ccopt -fPIC -ccopt -Wall -ccopt -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers" -ccopt -I -ccopt /home/mephage/Documents/git/github/ocamllabs/ocaml-ctypes/src/ctypes -ccopt -I -ccopt /home/mephage/Documents/git/github/ocamllabs/ocaml-ctypes/tests -o git2_stubs.o -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers" /home/mephage/Documents/git/github/ocamllabs/ocaml-ctypes/examples/git2/stub-generation/git2_stubs.c
ocamlfind  opt -I _build -linkpkg -principal -short-paths -g -ccopt "-I/home/mephage/.opam/4.07.1/lib/integers"  -package bytes -package str -package uri -package unix -package bigarray -package integers   _build/ctypes.cmxa _build/git2-stubs.cmxa -o _build/git2-cmd.native _build/examples/git2/stub-generation/git2_generated.cmx _build/examples/git2/stub-generation/git2_stub_cmd.cmx _build/examples/git2/stub-generation/git2_stubs.o -cclib -Wl,--no-as-needed -cclib -lgit2
make examples
